### ISSUE TITLE
Improve developer experience on Windows

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/bikespace#10]
@CodyGramlich has reported difficulty setting up the database. It would be nice to just be able to run ‘docker-compose up‘. I thought that was already set up, but I've never tested on Windows.

**Comment by j-rewerts** [comment]
@CodyGramlich what problems did you run into?

**Comment by CodyGramlich** [comment]
When I ran `docker build -t bikespace-db ./db && docker run -p5432:5432 bikespace-db` I would get this error:
`/usr/local/bin/docker-entrypoint.sh: /docker-entrypoint-initdb.d/qmkintersectiondb.sh: /bin/sh^M: bad interpreter: No such file or directory`

This error occurs due to the file having a dos format rather than a unix format and being unable to interpret the line endings, I think. To fix it, I opened the mkintersectiondb.sh with vim and typed `:set fileformat=unix` and then it worked.

On the upstream repo, they have this note, which doesn't specify which file to change:

> Note: Windows users might need to open some files in vim and set the fileformat to unix
> 
> ```viml
> :set fileformat=unix
> ```

I'm not sure why this change to the file can't be merged to master, unless doing this causing problems for Linux and Mac users.

**Comment by CodyGramlich** [comment]
Also, the command to activate the virtual environment is different on Windows.

Using command prompt it's
`"venv/Scripts/activate"`

and for PowerShell, it's
`venv/Scripts/activate`.

We can update this in our README

**Comment by CodyGramlich** [comment]
I made an issue for the mkintersectiondb.sh file on the upstream repo.
https://gitlab.com/bikespace/Bicycle-parking/issues/57

**Comment by CodyGramlich** [comment]
If I change mkintersectiondb.sh from CRLF to LF, git notices the change, but when I stage the changes, it no longer recognizes the changes:
```
git status
Changes not staged for commit:
	modified:   mkintersectiondb.sh
```
```
git add .
warning: LF will be replaced by CRLF in db/mkintersectiondb.sh.
The file will have its original line endings in your working directory
```
```
git status
nothing to commit, working tree clean
```

Also, if I change the file to LF and then checkout another branch, it will stay as LF. I'm not sure of a way to fix this other than having Windows users set mkintersectiondb.sh to LF locally.

**Comment by j-rewerts** [comment]
Were you able to switch git to automatically checking out files with LF on your laptop?

**Comment by CodyGramlich** [comment]
Yeah if I do `git clone https://github.com/CodyGramlich/bikespace.git --config core.autocrlf=input`, all my files are LF.

**Comment by CodyGramlich** [comment]
Another solution is to run dos2unix on mkintersectiondb.sh inside the container.
https://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/

**Comment by j-rewerts** [comment]
I think you can save your config globally so it does that for all repos.

Interesting idea about the dos2unix there! Lets see if we can get it working just for you before we change anything else.

**Comment by j-rewerts** [comment]
@CodyGramlich feel free to close if you feel your concerns have been addressed.

**Comment by j-rewerts** [comment]
Issue is resolved.
